services:
  discord-selfbot:
    build: .
    container_name: discord-selfbot
    restart: unless-stopped
    env_file: .env
    environment:
      - GUILD_ID=${GUILD_ID}
      - CHANNEL_ID=${CHANNEL_ID}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    command: node index.js
